action_id: trunk-single-player-auto-upgrade
date: 2023-09-19 11:34:10
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1695123250
full_timestamp:
  nanos: 370451000
  seconds: 1695123250
trunk_version: 1.16.0
